# fly.toml app configuration file generated for polychrome-nation on 2024-04-26T14:03:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'polychrome'
primary_region = 'ams'
kill_signal = 'SIGTERM'

[build]

[deploy]
strategy = "immediate"

[env]
DATABASE_PATH = "/data/octopus2.db"
PHX_HOST = 'polychrome.fly.dev'
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[services]]
protocol = "udp"
internal_port = 2342

[[services.ports]]
port = 2342


[[services]]
protocol = "udp"
internal_port = 8000

[[services.ports]]
port = 8000

[mounts]
source = "octopus_data"
destination = "/data"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 4
